apiVersion: v1
kind: PersistentVolume
metadata:
  name: helmflix-pv
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /home/helmflix/data  # This is the real path on your host machine
    type: DirectoryOrCreate
