apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: helmflix
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: manual  # Match the PV
  resources:
    requests:
      storage: 2Gi
